[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/google/go-jsonnet"
  version = "0.12.1"

[[constraint]]
  name = "github.com/pmezard/go-difflib"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[prune]
  go-tests = true
  unused-packages = true
